

export const FETCHING_URL = 'FETCHING_URL'
export const FETCH_URL_LINKS_SUCCESS = 'FETCH_URL_LINKS_SUCCESS'
export const FETCH_URL_LINKS_FAIL = 'FETCH_URL_LINKS_FAIL'
export const DELETE_URL_SUCCESS = 'DELETE_URL_SUCCESS'
export const DELETE_URL_FAIL = 'DELETE_URL_FAIl'
